### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#393]
Create a list of steps to make a release. For starters:
- [ ] update version numbers (Info.plist, CocoaPods, elsewhere)
- [ ] create a release branch
- [ ] create a pull request
- [ ] verify all sample apps work
- [ ] write a change log
- [ ] verify CocoaPods works
- [ ] verify readme is correct
- [ ] possibly add missing tests
- … add more as discovered

**Comment by EishanVijay** [comment]
# SDK Release Checklist

* update version numbers in project (use semantic versioning)
	- Info.plist —> Bundle versions string, short
	- CURRENT_PROJECT_VERSION

* update CocoaPods
	- `Mobile-Buy-SDK.podspec` —> `s.version = VERSION_NUMBER`

* go over repo's `README.md` and make changes if new version changed anything
	- Also check for broken links

* update `CHANGELOG.md` to reflect changes made to the new version of the SDK
	- `#VERSION_NUMBER (RELEASE_DATE)`
	- Features, Bug Fixes, Refactor, Tasks, Build Settings
		- one line description of each PR that went into the version as well as the PR number

* verify CocoaPods and Carthage work
	- CocoaPods
		-  Testing
			- it's best to test if the pod can be added successfully to an Xcode project
				- push updated podspec to branch
				-  create a new Xcode project which contains a Podfile
					- `pod 'Mobile-Buy-SDK', :git => 'https://github.com/Shopify/mobile-buy-sdk-ios.git'`
				- run `pod install` or `pod update`
	- Carthage
		-  Testing
			- add `github "Shopify/mobile-buy-sdk-ios"` to your Cartfile
			- run `carthage update` 

* make sure all tests are running locally

* verify that all sample apps work

* Create a release branch 
	- (follow naming convention: `release/VERSION_NUMBER`)

* Create a pull request (master <— release branch)
	- Title: “Mobile Buy SDK Version VERSION_NUMBER Release”
	- Description
		- Motivation behind SDK update
		- If new features are added to the SDK
		- List most significant external changes
			- List changes to APIs
		- List internal changes
		- How to configure the new version of the SDK (if setup has changed)
		- List all PRs that the pull request touches
			- don’t list if there are too many
		- Tag relevant people

####  * Merge in PR before continuing * 

- Create a SDK release on Github
	- Repo —> Releases
		- Draft a new release
		- Create new tag with VERSION_NUMBER
		- Set target to version release branch (?)
		- Release Title: VERSION_NUMBER
		- Description: quick summary of changelog
			- one line descriptions of major changes
				- dont put PR numbers
		- Provide download for the SDK in zip and tar.gz

- push update to CocoaPods
	- * you will need to be set up with Trunk in order to update the SDK pod * 
		- `edit Mobile-Buy-SDK.podspec`
			-	set the new version to VERSION_NUMBER
			-	set the new tag to VERSION_NUMBER
		-	run `pod lib lint` to to test the syntax of the .podspec file
		-	`git add -A && git commit -m "Release VERSION_NUMBER."`
		-	`git tag 'VERSION_NUMBER'`
		-	`git push --tags`
		-	`pod trunk push Mobile-Buy-SDK.podspec`

**Comment by EishanVijay** [comment]
cc @bgulanowski @davidmuzi @gabrieloc @dbart01

**Comment by davidmuzi** [comment]
This is great.  Should this go in a wiki page?

**Comment by EishanVijay** [comment]
I was thinking about making a wiki page on the SDK repo itself but then it would be public. Would it make sense to have this checklist private?

**Comment by EishanVijay** [comment]
I'll make a wiki page for this

**Comment by bgulanowski** [comment]
Awesome!

**Comment by krisorr** [comment]
@EishanVijay very nice, will add a similar one for Android
